steps:

- id: "Executando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Executando docker ps"
  name: "gcr.io/cloud-builders/docker"
  args: ['ps']
  
- id: "Executando compose"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'compose', 'install']

- id: "Criando arquivo .env"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']
  
- id: "Executando 'artisan key:generate'"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'php', 'artisan', 'key:generate']