version: '3'

services:

    app:
        build: .
        container_name: app
        #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://mysql:3306 -timeout 40s /usr/local/bin/entrypoint.sh
        #environment:
        #  - DB_HOST=mysql
        #  - DB_PORT=3306
        #  - DB_DATABASE=laravel
        #  - DB_USERNAME=root
        #  - DB_PASSWORD=root
        volumes:
          - ./laravel:/var/www
          - ./.docker:/var/www/.docker
        networks: 
          - app-network
        depends_on:
          - mysql
          - redis
          - composer

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - ./laravel:/var/www
        networks: 
          - app-network
        depends_on:
          - app

    redis:
        image: redis:alpine
        container_name: redis
        expose:
          - 6379
        networks: 
          - app-network

    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - ./.docker/mysqldata:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=laravel
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=root
        networks: 
          - app-network

    composer:
        image: "composer"
        container_name: composer
        networks: 
          - app-network

networks: 
  app-network:
      driver: bridge
